Security Basics
Chorniypistolet/spring-boot pull request #12
Opened 2024-07-02 16:48 UTC by Chorniypistolet

2024-07-02 17:13 UTC, Elena-Bruyako requested changes
Let's fix some comments

2024-07-02 17:13 UTC, Elena-Bruyako commented on pom.xml
> +			<artifactId>commons-beanutils</artifactId>
remove

See comment below

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/annotations/fieldMatch/FieldMatch.java
> +package mate.academy.spring.boot.annotations.fieldMatch;
```suggestion
package mate.academy.spring.boot.validation;
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/annotations/fieldMatch/FieldMatchValidator.java
> +        try {
```suggestion
        Object field = new BeanWrapperImpl(value).getPropertyValue(this. firstFieldName);
        Object fieldMatch = new BeanWrapperImpl(value).getPropertyValue(this. secondFieldName);
        return Objects.equals(field, fieldMatch);
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/user/UserLoginRequestDto.java
> +
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/user/UserLoginRequestDto.java
> +        @NotEmpty
```suggestion
        @NotBlank
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/user/UserRegistrationRequestDto.java
> +
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/user/UserResponseDto.java
> +
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, new HttpHeaders(), HttpStatus.BAD_REQUEST);
```suggestion
        return new ResponseEntity<>(body, new HttpHeaders(), HttpStatus.CONFLICT);
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +@ToString
It may cause some issues when you add Role in future HW

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    @Column(name = "first_name")
```suggestion
    @Column(nullable = false)
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    @Column(name = "last_name")
```suggestion
    @Column(nullable = false)
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    @Column(name = "shipping_address")
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    @Column(name = "is_deleted", nullable = false)
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/repository/user/UserRepository.java
> +
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/UserService.java
> +
```suggestion
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/AuthenticationController.java
> +       return authenticationService.login(requestDto);
You don't need to implement /login endpoint in this HW!


See the task description

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +        if(userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
```suggestion
        if(userRepository.existsByEmail(request.email())) {
```

it's better

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("Cant register User");
```suggestion
            throw new RegistrationException(String.format("User with this email: %s already exists", request.email()));
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +        if (!requestDto.getPassword().equals(requestDto.getRepeatPassword())) {
remove

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +        User user = new User();
```suggestion
        User user = mapper.toUser(request);
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: firstName
```suggestion
                  name: first_name
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: lastName
```suggestion
                  name: last_name
```

2024-07-02 17:13 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: shippingAddress
```suggestion
                  name: shipping_address
```

2024-07-04 05:51 UTC, Elena-Bruyako requested changes
Some comments should be fixed

2024-07-04 05:51 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    Long id;
```suggestion
    private Long id;
```

check all fields

2024-07-04 05:51 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    @Column(name = "is_deleted", nullable = false)
not fixed

2024-07-04 05:51 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/mapper/UserMapper.java
> +
```suggestion
```

2024-07-04 05:51 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +        user.setEmail(requestDto.getEmail());
you already map request to model, don't need to use set methods

2024-07-04 05:51 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/validation/FieldMatchValidator.java
> +        try {
remove

2024-07-04 05:51 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/validation/FieldMatchValidator.java
> +        } catch (Exception e) {
remove

2024-07-05 12:30 UTC, Elena-Bruyako requested changes
see pr

2024-07-05 12:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +@Data
don't use Data with entities

2024-07-05 12:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    boolean isDeleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-07-05 12:30 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/repository/user/UserRepository.java
> +    Optional<User> existsByEmail(String email);
```suggestion
    boolean existsByEmail(String email);
```

2024-07-09 19:41 UTC, sarakhmen approved these changes

2024-07-11 16:44 UTC, merged