HW
Chorniypistolet/spring-boot pull request #13
Opened 2024-08-01 18:04 UTC by Chorniypistolet

2024-08-04 15:28 UTC, Elena-Bruyako requested changes
see comments

2024-08-04 15:28 UTC, Elena-Bruyako commented on pom.xml
> +			<version>4.29.0</version>
```suggestion
			<version>${liquibase.version}</version>
```

spring boot parent provides this version

2024-08-04 15:28 UTC, Elena-Bruyako commented on pom.xml
> +			<version>3.3.2</version>
```suggestion
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/config/SecurityConfig.java
> +                                .requestMatchers("/auth/**", "/error")
```suggestion
                                .requestMatchers("/auth/**", "/error", "/swagger-ui/**", "/v3/api-docs/**")
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/BookController.java
> +@RequestMapping("/api/books")
```suggestion
@RequestMapping("/books")
```

just add `server.servlet.context-path=/api` to application.properties

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/exception/BasicCredentialException.java
> +public class BasicCredentialException extends RuntimeException{
Where do you use it?

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    private Set<Role> roles;
```suggestion
    private Set<Role> roles = new HashSet<>();
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
```suggestion
    @ManyToMany
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +        return List.of();
```suggestion
        return roles;
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Role.java
> +public class Role {
```suggestion
public class Role implements GrantedAuthority {
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/security/CustomUserDetailsService.java
> +        return new org.springframework.security.core.userdetails.User(user.getEmail(), user.getPassword(), authorities);
```suggestion
        return repository.findByEmail(username)
                .orElseThrow(() -> new EntityNotFoundException(
                        "Can't find user by email: " + username));
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +        User savedUser = userRepository.save(user);
```suggestion
        userRepository.save(user);
```

2024-08-04 15:28 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +        return userMapper.toUserResponse(savedUser);
```suggestion
        return userMapper.toUserResponse(user);
```

2024-08-06 09:34 UTC, Elena-Bruyako requested changes
see comments
You have conflicts in your branch, please fix them

2024-08-06 09:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/AuthenticationController.java
> +    public UserResponseDto register(@RequestBody UserRegistrationRequestDto requestDto) throws RegistrationException {
```suggestion
    public UserResponseDto register(@RequestBody @Valid UserRegistrationRequestDto requestDto) throws RegistrationException {
```

2024-08-06 09:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Role.java
> +        return null;
why is null?

2024-08-06 09:34 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/security/CustomUserDetailsService.java
> +        Set<GrantedAuthority> authorities = user.getRoles().stream()
see previous comment

2024-08-06 09:37 UTC, Chorniypistolet commented on src/main/java/mate/academy/spring/boot/security/CustomUserDetailsService.java
> +        Set<GrantedAuthority> authorities = user.getRoles().stream()
but if I don't use this variant, then I have problems with endpoints that are available only to the admin

2024-08-08 14:20 UTC, okuzan requested changes

2024-08-08 14:20 UTC, okuzan commented on src/main/resources/db/changelog/changes/08-update-users-table.yaml
> +              WHERE id NOT IN (SELECT user_id FROM users_roles)
```suggestion
            sql: |
              INSERT INTO users_roles (user_id, role_id)
              SELECT id, 1
              FROM users
              WHERE id NOT IN (SELECT user_id FROM users_roles)

```
![image](https://github.com/user-attachments/assets/8d497a9d-3664-43f2-991b-36281c7d2002)
go through the files in your PR, add empty line where needed

2024-08-08 14:20 UTC, okuzan commented on src/main/resources/db/changelog/changes/06-add-admin-users-table.yaml
> +                  value: "$2a$10$Y4q3wbO7NeW8eWRaE0jqMuIKIlmMNC1qt6ypQdTNPtgKq00rk3.Ki"
add password in plantext as comment, it's useless otherwise

2024-08-09 08:37 UTC, Elena-Bruyako approved these changes

2024-08-09 08:37 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/BookServiceImpl.java
> +    @Transactional(readOnly = true)
redundant

2024-08-09 17:03 UTC, merged