Spring Boot practice: Add Category model
Chorniypistolet/spring-boot pull request #15
Opened 2024-08-21 18:27 UTC by Chorniypistolet

2024-08-22 13:23 UTC, Elena-Bruyako requested changes
see comments

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/CategoryController.java
> +    private final BookMapper bookMapper;
```suggestion
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/CategoryController.java
> +    public CategoryDto createCategory(@RequestBody @Valid CategoryDto categoryDto) {
```suggestion
    public CategoryDto createCategory(@RequestBody @Valid CategoryRequestDto categoryDto) {
```

create CategoryRequestDto withou id field

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/CategoryController.java
> +    public CategoryDto updateCategory(@PathVariable Long id, @RequestBody @Valid CategoryDto categoryDto) {
```suggestion
    public CategoryDto updateCategory(@PathVariable Long id, @RequestBody @Valid CategoryRequestDto categoryDto) {
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/CategoryController.java
> +
```suggestion
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/mapper/CategoryMapper.java
> +    Category toEntity(CategoryDto categoryDTO);
```suggestion
    CategoryDto toDto(Category category);
    
    Category toEntity(CategoryDto categoryDto);
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Book.java
> +            name = "book_category",
```suggestion
            name = "books_categories",
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Category.java
> +    private Set<Book> books = new HashSet<>();
```suggestion
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Category.java
> +    private boolean deleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Category.java
> +@SQLRestriction("deleted = false")
```suggestion
@SQLRestriction("is_deleted = false")
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Category.java
> +@SQLDelete(sql = "UPDATE categories SET deleted = true WHERE id=?")
```suggestion
@SQLDelete(sql = "UPDATE categories SET is_deleted = true WHERE id=?")
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/security/JwtAuthenticationFilter.java
> +        String bearerToken = request.getHeader(AUTHORIZATION);
```suggestion
        String bearerToken = request.getHeader(HttpHeaders.AUTHORIZATION);
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/security/JwtAuthenticationFilter.java
> +    private static final int INDEX = 7;
```suggestion
    private static final String TOKEN_HEADER = "Bearer ";
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/security/JwtAuthenticationFilter.java
> +            return bearerToken.substring(INDEX);
```suggestion
            return bearerToken.substring(TOKEN_HEADER.length());
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/security/JwtAuthenticationFilter.java
> +        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(BEARER)) {
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(TOKEN_HEADER)) {
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/CategoryService.java
> +    void deleteById(Long id);
```suggestion
    List<CategoryDto> findAll();
    
    CategoryDto getById(Long id);
    
    CategoryDto save(CategoryDto categoryDto);
    
    CategoryDto update(Long id, CategoryDto categoryDto);
    
    void deleteById(Long id);
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/CategoryServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Category not found"));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("No such a category with id: " + id));
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/CategoryServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Category not found"));
add id to message

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/CategoryServiceImpl.java
> +        category.setDescription(categoryDto.getDescription());
```suggestion
        categoryMapper.updateCategoryFromDto(categoryDto, category);
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/CategoryServiceImpl.java
> +        categoryRepository.save(category);
```suggestion
        categoryRepository.deleteById(id);
```

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/09-create-categories-table.yaml
> +                  name: deleted
rename

2024-08-22 13:23 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/10-create-book_category-table.yaml
> +            tableName: book_category
rename

2024-08-26 09:33 UTC, MentorMateAcademy requested changes

2024-08-26 09:33 UTC, MentorMateAcademy commented on src/main/java/mate/academy/spring/boot/repository/book/BookRepository.java
> +@Repository
```suggestion
```

2024-08-26 09:33 UTC, MentorMateAcademy commented on src/main/java/mate/academy/spring/boot/repository/book/BookRepository.java
> +@Repository
Not mandatory

2024-08-26 09:33 UTC, MentorMateAcademy commented on src/main/java/mate/academy/spring/boot/repository/category/CategoryRepository.java
> +@Repository
```suggestion
```

2024-08-26 09:33 UTC, MentorMateAcademy commented on src/main/java/mate/academy/spring/boot/service/BookService.java
> +import mate.academy.spring.boot.dto.book.*;
don`t use * in imports

2024-08-26 09:33 UTC, MentorMateAcademy commented on src/main/java/mate/academy/spring/boot/service/impl/BookServiceImpl.java
> +import mate.academy.spring.boot.dto.book.*;
fix imports

2024-08-28 12:23 UTC, Elena-Bruyako requested changes
see comments

2024-08-28 12:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/CategoryService.java
> +@Service
```suggestion
```

2024-08-28 12:23 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/CategoryServiceImpl.java
> +        category = categoryMapper.updateCategoryFromDto(categoryRequestDto, category);
```suggestion
        categoryMapper.updateCategoryFromDto(categoryRequestDto, category);
```

2024-08-28 20:07 UTC, sarakhmen approved these changes

2024-08-29 16:47 UTC, merged