Spring Boot practice: Add ShoppingCart
Chorniypistolet/spring-boot pull request #17
Opened 2024-09-09 17:22 UTC by Chorniypistolet

2024-09-10 07:45 UTC, Elena-Bruyako requested changes
see comments

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +    ShoppingCartDto addBookToCart(@AuthenticationPrincipal User user, @RequestBody CartItemRequestDto cartItemRequestDto) {
```suggestion
    public ShoppingCartDto addBookToCart(@AuthenticationPrincipal User user, @RequestBody @Valid CartItemRequestDto cartItemRequestDto) {
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +    public ShoppingCartDto getShoppingCart (@AuthenticationPrincipal User user){
```suggestion
    public ShoppingCartDto getShoppingCart(@AuthenticationPrincipal User user){
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +    }
```suggestion
    }
    
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +    public ShoppingCartDto updateCartItemQuantity (@PathVariable("id") Long id,
```suggestion
    public ShoppingCartDto updateCartItemQuantity(@PathVariable("id") Long id,
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +            @RequestBody CartItemRequestDto cartItemRequestDto){
```suggestion
            @RequestBody @Valid CartItemRequestDto cartItemRequestDto){
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +    public void deleteCartItem (@PathVariable Long id){
```suggestion
    public void deleteCartItem(@PathVariable Long id){
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +    public void clearCart(@AuthenticationPrincipal User user) {
remove

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/cartItem/CartItemRequestDto.java
> +    @NotNull
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/cartItem/CartItemRequestDto.java
> +    @NotNull
```suggestion
    @NotNull
    @Positive
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/cartItem/CartItemRequestDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +    private Integer quantity;
```suggestion
    private int quantity;
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +    @Column(nullable = false)
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/ShoppingCart.java
> +    @JoinColumn(name = "user_id", nullable = false)
```suggestion
    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/repository/CartItem/CartItemRepository.java
> +
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/ShoppingCartService.java
> +
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/UserService.java
> +    User findById(Long id);
remove

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        shoppingCart.setCartItemSet(cartItemRepository.findByShoppingCartIdWithBook(shoppingCart.getId()));
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        User user = userService.findById(userId);
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +    @Override
add Transactional where is needed

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        Book book = bookMapper.toEntity(bookService.findById(cartItemRequestDto.getBookId()));
```suggestion
        Book book = bookRepository.findById(cartItemRequestDto.getBookId())
                .orElseThrow(()....
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        ShoppingCart shoppingCart = shoppingCartRepository.findByIdWithItems(user.getId())
```suggestion
        ShoppingCart shoppingCart = shoppingCartRepository.findByUserId(user.getId())
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        }
```suggestion
        }
        shoppingCartRepository.save(shoppingCart);
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +            cartItemRepository.save(newCartItem);
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +            cartItemRepository.save(existingCartItem);
```suggestion
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +                .orElse(null);
you can use 
```suggestion
                .ifPresentOrElse(item ->item.setQuantity(item.getQuantity() + cartItemRequestDto.getQuantity()),
                     () -> create method where you set book to cartItem and add cartItem to shop cart
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id)
```suggestion
        ShoppingCart cart = shoppingCartRepository.findByUserId(userId);
        CartItem cartItem = cartItemRepository.findByIdAndShoppingCartId(cartItemId, cart.getId())...
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        cartItemRepository.save(cartItem);
```suggestion
        shoppingCartRepository.save(cart);
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toDto(cartItem.getShoppingCart());
```suggestion
        return shoppingCartMapper.toDto(cart);
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +        CartItem cartItem = cartItemRepository.findById(id)
```suggestion
        ShoppingCart shoppingCart = repository.findByUserId(userId);
        CartItem cartItem = itemRepository.findByIdAndShoppingCartId(itemId, shoppingCart.getId())....
```

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +    public void clearCart(Long userId) {
remove

2024-09-10 07:45 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/UserServiceImpl.java
> +    public User findById(Long id) {
remove

2024-09-11 11:49 UTC, Elena-Bruyako requested changes
one comment

2024-09-11 11:49 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +    public Integer getQuantity() {
why do you need this get?

2024-09-12 08:32 UTC, okuzan requested changes
some comments

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +
```suggestion
```

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/dto/cartItem/CartItemRequestDto.java
> +    private Long bookId;
```suggestion
    private long bookId;
```
let's just use primitive, we won't need NotNull

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("CartItem not found with id " + id));
duplicated logic, better extract to private methods

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/service/impl/ShoppingCartServiceImpl.java
> +
```suggestion
```

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/service/ShoppingCartService.java
> +
```suggestion
```

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/repository/shoppingCart/ShoppingCartRepository.java
> +
```suggestion
```

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/repository/CartItem/CartItemRepository.java
> +
```suggestion
```

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/model/CartItem.java
> +
```suggestion
```

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/model/ShoppingCart.java
> +@ToString
Be careful with using lombok's toString on JPA entities, you have lazily loaded depended entities, which can cause lazy init exception, use @ToString(exclude = "cartItemSet")

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/mapper/CartItemMapper.java
> +
```suggestion
```
don't leave an empty line before class ends

2024-09-12 08:32 UTC, okuzan commented on src/main/java/mate/academy/spring/boot/dto/shoppingCart/ShoppingCartDto.java
> +@Setter
it's ok to just use @Data on all DTO

2024-09-13 06:56 UTC, Elena-Bruyako requested changes
see comments

2024-09-13 06:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/ShoppingCartController.java
> +
not fixed

2024-09-13 06:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/cartItem/CartItemRequestDto.java
> +    @Positive
```suggestion
    @Positive
    @NotNull
```

2024-09-13 06:56 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/cartItem/CartItemRequestDto.java
> +    private long bookId;
```suggestion
    private Long bookId;
```

2024-09-14 05:53 UTC, Elena-Bruyako approved these changes

2024-09-15 11:11 UTC, merged