Add Order
Chorniypistolet/spring-boot pull request #18
Opened 2024-09-28 08:03 UTC by Chorniypistolet

2024-10-02 13:06 UTC, Elena-Bruyako requested changes
see comments

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/controller/OrderItemController.java
> +public class OrderItemController {
replace all endpoints to OrderController

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/order/OrderRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/dto/status/StatusRequestDto.java
> +    @NotNull
```suggestion
    @NotBlank
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/mapper/OrderItemMapper.java
> +
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/mapper/OrderMapper.java
> +
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/OrderItem.java
> +@ToString
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/Status.java
> +
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/model/User.java
> +    private Set<Order> orders;
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/repository/order/OrderRepository.java
> +
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/OrderService.java
> +
```suggestion
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/OrderItemServiceImpl.java
> +public class OrderItemServiceImpl implements OrderItemService {
replace logic to OrderService

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/OrderServiceImpl.java
> +                .toList();
```suggestion
        return orderMapper.toOrderDtoList(orderRepository.findAllByUserId(userId, pageable));
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/OrderServiceImpl.java
> +    public List<OrderDto> getAllOrdersByUserId(Long id) {
```suggestion
    public List<OrderDto> getAllOrdersByUserId(Long id, Pageable pageable) {
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/OrderServiceImpl.java
> +        orderRepository.save(order);
```suggestion
        Order order = orderRepository.findById(orderId)
                .map(o -> {
                    o.setStatus(Status.valueOf(orderDto.status()));
                    return o;
                })
                .orElseThrow(() -> new EntityNotFoundException(
                        String.format("Order with id: %d not found", orderId)
                ));
                return orderMapper.toUpdateDto(orderRepository.save(order));
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/spring/boot/service/impl/OrderServiceImpl.java
> +                .orElseThrow(() -> new EntityNotFoundException("Shopping cart not found for user " + userId));
```suggestion
                .orElseThrow(() -> new EntityNotFoundException("Shopping cart not found for user " + userId));
                if (shoppingCart.getCartItems().isEmpty()) { 
                    throw new OrderProcessingException
```

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/14-create-orders-table.yaml
> +        - createIndex:
remove creating index

2024-10-02 13:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/16-update-orders-table.yaml
> +        - modifyDataType:
remove this changeSet and id: 17 also
modify datatype columnName: status in existing changesets

2024-10-07 09:03 UTC, ahoienko approved these changes
Good job!

2024-10-08 17:49 UTC, merged